### ISSUE TITLE
Project State

### ISSUE THREAD

**Issue by wackmf** [wfut/wfut#6]
I noticed some missing 107 files and was curious if this would prevent the mod from working. I attempted to get the mod running on UT 436, but the only thing I see is Weapons Factory listed in the Category Type under Practice Session. It has been so long...Are the install instructions up to date?

On a side note, I bought wfut.net and have it redirecting to this repository.

**Comment by colkassad** [comment]
Thanks for the redirect...I had actually just let that domain expire some months back!

What 107 files did you find that were missing? 

I have to go over the install instructions and unfortunately I don't have UT99 installed atm. They *should* be up to date...I believe 436 was live when we were still developing WFUT, please correct me if I am mistaken. We were pretty good about that sort of stuff back in the day.

Remember that WFUT worked with all base game CTF maps, see if it works by starting a practice session with a standard CTF map.

**Comment by wackmf** [comment]
Step 5 is where I do not see a Configure Classes button. The Game Category shows up, but the box under is empty. The maps also show up in the map list. Are you on steam? I can gift a copy of UT99 to you if you can help me figure this out. I have a couple of old demo files I want to get published on Youtube.

Also, I don't know if you guys realize, but this mod has given me life long friends. I still talk and visit with Ghost, DontKnow, Spiritual Assassins and others. We always reminisce. I even put up the old website from 2001 http://www.woprclan.org 

This is definitely a keeper: http://www.woprclan.org/pics/wack/wack07.html

Setting up WFUT to use the WFUT Player Classes:
----------------------------------------------
1) Start up UT normally
2) Open the game window (either start practice session, or start mutliplayer game)
3) Select "Weapons Factory" as the game category
4) Select the "Setting" tab
5) Click on the "Configure Classes" button
6) Select "WF Dev. classes" for each team

**Comment by colkassad** [comment]
That site brings back memories (lol at the screenshot)! I still talk with Ob1 here and there. It's been a while though. I do own UT99 so no need to gift. I just need to find time to look through this issue. I know I had WFUT up and running about a year ago but it was from an installer I think. So I will have to look over and verify the docs, and try to compile from source and get it running that way. Please bear with me while I try to find time for that.

**Comment by colkassad** [comment]
OK, so here is how I got it to work:

1. Clone the repo and copy the following folders to the UT directory:
    1. System
    1. WFCode
    1. WFMedia
    1. WFSystem
    1. WFBonusPackCTFMapData
    1. WFStockCTFMapData
2. In the _UT Directory_\System folder, open UnrealTournament.ini and add the following to the end of the [Editor.EditorEngine] section:

EditPackages=WFMedia
EditPackages=WFSystem
EditPackages=WFCode

3. Navigate via command prompt to _UT Directory_\System and type "ucc make", wait for it to compile
4. Start Unreal Tournament and start a new multiplayer game (Multiplayer > Start New Multiplayer Game)
5. Under the Match tab, select Category: Weapons Factory, and Game Type: Weapons Factory
6. Choose a map, doesn't matter which
7. Select the Bots tab, and set Min. Total Players to something greater than 1 
8. Start the game, you should get a Weapons Factory menu for choosing your team.

I will try and update the docs as they are in fact a bit out of date!

**Comment by wackmf** [comment]
That did the trick!

I wasn't including the EditPackages lines and was not compiling. All works great now
